#define white 2
#define blue 1
#define green 0 'start
#define orange 7 'reset
#define red 4 'stop
#define waitForBut .4
#define showtime 5

Global Integer num_token
Global Integer num_block
Global Integer id_token
Global Integer id_block
Global Integer id


Global Double height_feeder
Global Double asobi


#define vacuum 8
#define thick 6.0
#define height_feeder 5.0
#define offset_y 30

#define block 1
#define token 0

'''
#define platform_height 10.5
#define amount 6
'''
